[package]
name = "netlink-rs"
version = "0.0.1"
authors = ["crhino <piraino.chris@gmail.com>"]
license = "MIT"
description = "Rust netlink library"

[dependencies]
libc = "^0.2"
byteorder = "^0.5"

[features]
default = []
